#!/bin/bash
# ec2ssh

# Manually delete files from this folder to flush cached data.
cache='/tmp/ec2ssh.cache'


check_dependencies () {
    if ! command -v jq > /dev/null ; then
        echo "Please install jq (https://stedolan.github.io/jq/)" ; exit 1
    fi
    if ! command -v fzf > /dev/null ; then
        echo "Please install fzf (https://github.com/junegunn/fzf)" ; exit 1
    fi
    if ! command -v aws > /dev/null ; then echo "Please install aws" ; exit 1 ; fi
}


usage () {
    cat <<.
Usage: $(basename "$0")
    -h,--help       Show this message and exit.
    -e,--env        Work on this environment (default: prod).
    -l <login_name> Pass this option to SSH. Login with this username.
.
}

parse_opts () {
    tempopt=$(getopt --name $(basename "$0") -o u,h,e:,l: -l usage,help,env: -- "$@")
    # Finish if received some unknown option.
    if [ $? != 0 ] ; then usage && exit 1 ; fi

    eval set -- "$tempopt"

    # Default values.
    env="prod"
    ssh_opts=""

    # Parse named options.
    while true ; do
        case "$1" in
            -u|--usage|-h|--help) usage && exit ;;
            -e|--env) env="$2" ; shift 2 ;;
            -l) ssh_opts="${ssh_opts} -l $2" ; shift 2 ;;
            --) shift 1 ; break ;;
            *) echo "Internal error!" >&2 ; exit 1 ;;
        esac
    done

    # Parse arguments.
    if [ $# != 0 ] ; then usage && exit 1 ; fi
}


get_ec2roles () {
    # Retrieves all EC2 tags "Role"
    aws ec2 describe-instances --no-paginate --output json \
        --query "Reservations[].Instances" \
        --filters "Name=tag:Env,Values=${env}" "Name=instance-state-name,Values=running" \
    | jq -r '.[][].Tags[] | select(.Key=="Role") | .Value' \
    | sort | uniq
}


ec2roles () {
    # Remove empty cache files.
    if [ ! -s "${cache}/${env}.roles" ] ; then
        rm -f "${cache}/${env}.roles"
    fi
    if [ ! -f "${cache}/${env}.roles" ] ; then
        get_ec2roles > "${cache}/${env}.roles"
    fi
    fzf --prompt "Role> " < "${cache}/${env}.roles"
}


ec2instances () {
    aws ec2 describe-instances --no-paginate --output json \
        --filters "Name=tag:Env,Values=${env}" "Name=tag:Role,Values=${role}" \
                  "Name=instance-state-name,Values=running" \
        --query "Reservations[].Instances"
}


jq_name_and_ip () {
    cat <<.
        .[][] |
        # enrich all tags with IP address
        .Tags[] + { "Ip": .PrivateIpAddress } |
        # keep only tags with Key="Name"
        select(.Key=="Name") |
        [ .Value, .Ip ] | @tsv
.
}


check_dependencies
parse_opts "$@"

# Create cache dir, if needed.
[ -d ${cache} ] || mkdir ${cache}

role=$(ec2roles)
host_and_addr=$(ec2instances | jq -r -f <(jq_name_and_ip) | fzf -n1 --prompt "Host> ")
addr=$(echo "${host_and_addr}" | awk '{print $2}')

# Remove the local functions from global env.
unset -f jq_name_and_ip
unset -f ec2instances
unset -f ec2roles
unset -f get_ec2roles


echo "${host_and_addr}"
ssh ${ssh_opts} "${addr}"
